### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by fulldecent** [REGA-RS/ERC721SmartToken#2]
Please explain how we can inspect these transactions from off chain.

Does this work using events? How should we interpret those events?

**Comment by sevriugin** [comment]
Good point. Need to add more events. There are several [defined](https://github.com/REGA-RS/ERC721SmartToken/blob/ac4f3049baf4efac1f910719be2bab93b2af8530/contracts/ERC721.sol#L76) but need to elaborate

**Comment by sevriugin** [comment]
Done, and also some Events info in [Help](https://github.com/REGA-RS/ERC721SmartToken/blob/master/help.md#events)
